### ISSUE TITLE
Create your artifacthub-pkg.yml based on the metadata.yml

### ISSUE THREAD

**Issue by jvanz** [nlamirault/probes-policy#10]
Hi! I'm a Kubewarden maintainer and I would like to share with you that in recent version of our tooling and Github actions we simplify the process of releasing policies by generating the `artifacthub-pkg.yml` file automatically based on the `metadata.yml` file. We would love help you migrating your policy to the new tools. You can see example of how to do it here:

https://github.com/kubewarden/user-group-psp-policy
https://github.com/kubewarden/pod-privileged-policy
https://github.com/kubewarden/safe-labels-policy

Notice that the new Gihub action publishes the Artifacthub files into [another branch](https://github.com/kubewarden/github-actions/blob/main/.github/workflows/reusable-release-policy-rust.yml#L53-L65). This is required because the update in the file must occurs **after** the policy artifact is built, published and signed. Otherwise, Artifacthub scan job can detect the change before the signing of the policy OCI artifact. Then, showing the policy as not signed in the Artifact hub web page.

**Comment by jvanz** [comment]
Other question, do you consider to publish the policy at [artifacthub](https://artifacthub.io/)?

**Comment by nlamirault** [comment]
yes @jvanz i would like to publish at ArtifactHub.
